### ISSUE TITLE
windows binary not working

### ISSUE THREAD

**Issue by abioneperhobby** [myint/perceptualdiff#11]
windows binary can be downloaded here https://sourceforge.net/projects/pdiff/ but running perceptualdiff.exe i got this error.

![image](https://cloud.githubusercontent.com/assets/2149815/20528820/f6554b98-b0cd-11e6-84a8-732a185debae.png)

should i compile it ?

thanks

**Comment by myint** [comment]
I haven't dealt with the Windows binary before. And this is repository is just a fork. I don't have control over what is on the original page.

**Comment by myint** [comment]
Yes, I think you probably should compile it.

**Comment by abioneperhobby** [comment]
thanks
