### ISSUE TITLE
Alpha channel is ignored

### ISSUE THREAD

**Issue by abioneperhobby** [myint/perceptualdiff#12]
![immagine2](https://cloud.githubusercontent.com/assets/2149815/20530905/347d78da-b0d5-11e6-90a7-0800a9c69ccd.png)
![immagine1](https://cloud.githubusercontent.com/assets/2149815/20530904/347d4a68-b0d5-11e6-97fc-94da9175f594.png)

qa-Latitude-E6510 Scrivania # perceptualdiff --verbose immagine1.png immagine2.png 
Field of view is 45 degrees
Threshold pixels is 100 pixels
The Gamma is 2.2
The Display's luminance is 100 candela per meter squared
Converting RGB to XYZ
Constructing Laplacian Pyramids
Performing test
PASS: Images are perceptually indistinguishable
0 pixels are different
qa-Latitude-E6510 Scrivania # 

but the two images are different.

**Comment by myint** [comment]
`perceptualdiff` only compares the RGB channels. It looks like your images only differ in the alpha channel.

**Comment by myint** [comment]
It should detect the difference now:

![diff](https://cloud.githubusercontent.com/assets/1235108/20550405/2ccf8d5c-b0ea-11e6-929b-cdedd49e4d68.png)
