### ISSUE TITLE
fingerprinting images for finding near duplicates

### ISSUE THREAD

**Issue by fenchu** [myint/perceptualdiff#13]
Hi 

This is a feature requests, but if you have a great idea on doing it I would be very happy.

Is there a way I can fingerprint an image so I can compare fingerprinting instead of comparing whole images all the time, this is for nearly similar images, the identical have been taken care of with sha-hashing.

I'm trying to find near duplicates in a 3mill+ image database using `preceptualdiff --threshold 50000 --scale` it works fine, but very slow. We had a SAN crash and found backup in archive mode (means adding, not moving when things have been rewritten, giving us 600K obsolete duplicates).

I've done heavy optimizing and is down to 80K root path images that need to be compared for near duplicates (mostly scaled and color and alpha tunes and some images in path removed), but it is still (80K+80K)/2 = 3.2Bill comparisons to be made. The SSD san manages to run 16 threads in parallel giving me 32 comparisons/sec which will take 542 days.

**Comment by jterrace** [comment]
The diffing here is very different from an image fingerprinting approach. See here for some things to explore:
https://stackoverflow.com/q/596262/624900
