### ISSUE TITLE
perceptualdiff API

### ISSUE THREAD

**Issue by JesusIslam** [myint/perceptualdiff#3]
Does it? Or will it be added? Base64 input is fine too.

**Comment by jterrace** [comment]
Can you clarify what you mean? Do you want to pipe stdout ? Can you give an example command?

**Comment by JesusIslam** [comment]
Ah, sorry, I think I was drunk back then.

So I want to call perceptualdiff from my program, but there isn't any file generated, only two binary of the images. How do I compare these two binary using perceptualdiff?

I hope this will clarify my original question. Thank you.

**Comment by jterrace** [comment]
Ah, so really what you want is a programmatic API?

**Comment by JesusIslam** [comment]
Kinda, it would be very great.
